/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gomi;

/**
 *
 * @author jonyg
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setLayout(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1);
        jSeparator1.setBounds(116, 0, 2, 391);

        jButton2.setText("Solicitar coleta");
        add(jButton2);
        jButton2.setBounds(136, 32, 212, 34);

        jButton8.setText("Agendar coleta");
        add(jButton8);
        jButton8.setBounds(136, 84, 212, 34);

        jLabel1.setText("ULTIMAS COLETAS");
        add(jLabel1);
        jLabel1.setBounds(190, 131, 91, 14);

        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1);
        jScrollPane1.setBounds(136, 156, 212, 197);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2);
        jSeparator2.setBounds(358, 0, 2, 353);

        jPanel2.setLayout(null);

        jLabel2.setText("Label para imagem");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 50, 100, 14);

        add(jPanel2);
        jPanel2.setBounds(366, 11, 208, 133);

        jLabel3.setText("OLA USUARIO");
        add(jLabel3);
        jLabel3.setBounds(430, 160, 69, 14);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator3);
        jSeparator3.setBounds(366, 217, 218, 10);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jButton1.setText("jButton1");
        jPanel3.add(jButton1);
        jButton1.setBounds(40, 10, 44, 32);

        jButton3.setText("jButton3");
        jPanel3.add(jButton3);
        jButton3.setBounds(40, 60, 44, 36);

        jButton4.setText("jButton4");
        jPanel3.add(jButton4);
        jButton4.setBounds(40, 120, 45, 35);

        jButton5.setText("jButton5");
        jPanel3.add(jButton5);
        jButton5.setBounds(40, 180, 45, 35);

        jButton6.setText("jButton6");
        jPanel3.add(jButton6);
        jButton6.setBounds(40, 240, 45, 38);

        jButton7.setText("jButton7");
        jPanel3.add(jButton7);
        jButton7.setBounds(40, 300, 45, 39);

        add(jPanel3);
        jPanel3.setBounds(0, 0, 120, 360);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
